HuloToys-Front-End/ViewModels/LoginViewModel.cs
namespace HuloToys_Front_End.ViewModels
{
    public class LoginViewModel
    {
    }
}

HuloToys-Front-End/viewcomponents/SearchViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB.CMS.ViewComponents
{
    public class SearchViewComponent : ViewComponent
    {
       
        public SearchViewComponent()
        {
           
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }

       
    }
}

HuloToys-Front-End/Views/Shared/_AccountManagementLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/jquery-ui.css">
    <link rel="stylesheet" href="/assets/css/select2.min.css">
    <link rel="stylesheet" href="/assets/css/lightgallery-bundle.css" />
    <link rel="stylesheet" href="/assets/css/main.min.css">
    <link rel="stylesheet" href="/custom/site.css">

    <link rel="stylesheet" href="/css/site.css">

    <title>@ViewData["Title"]</title>
    <link type="image/x-icon" href="~/images/img-search.png" rel="shortcut icon" />
    <!-- CSS-->

</head>
<body>
    <partial name="_Header" />
    <partial name="_Login" />

    <section id="main">
        <section class="section-qly-taikhoan">
            <div class="container">
                <div class="box-quanlytaikhoan">
                    <div class="menu-left-user placeholder">
                        <partial name="_MenuLeftUser" />
                    </div>
                    <div class="content-left-user">
                        @RenderBody()

                    </div>
                </div>
            </div>
        </section>
    </section>

    <partial name="/Views/Client/UpdateAddress.cshtml" />
    <partial name="_Footer" />
    <button class="backToTopBtn"></button>
    <partial name="_Lightbox" />
    <button class="backToTopBtn"></button>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/swiper-bundle.min.js"></script>
    <script src="/assets/js/jquery-ui.js"></script>
    <script src="/assets/js/select2.min.js"></script>
    <script src="/assets/js/lightgallery.min.js"></script>
    <script src="/assets/js/common.js"></script>
    <script asp-append-version="true" src="/custom/jquery.magnific-popup.min.js"></script>

    <script asp-append-version="true" src="/modules/constants.js"></script>
    <script asp-append-version="true" src="/modules/services.js"></script>
    <script asp-append-version="true" src="/modules/global.js"></script>
    <script asp-append-version="true" src="/modules/account_management_global.js"></script>
    <script asp-append-version="true" src="/assets/js/select2.min.js"></script>
    <!-- lightgallery-->
    <script src="/assets/js/lightgallery.min.js"></script>
    <script src="/assets/js/video.min.js"></script>
    <script src="/assets/js/lightgallery.umd.js"></script>
    <script src="/assets/js/lg-video.umd.js"></script>
    <script src="/assets/js/lg-thumbnail.min.js"></script>
    <!-- end lightgallery-->

    <!-- Modules-->
    <script asp-append-version="true" src="/modules/order_address.js"></script>
    <script asp-append-version="true" src="/modules/account.js"></script>
    <script asp-append-version="true" src="/modules/home_product.js"></script>
    <script asp-append-version="true" src="~/modules/support.js"></script>
    <script asp-append-version="true" type="text/javascript" src="~/modules/feedback.js"></script>
    <script src="https://accounts.google.com/gsi/client" async></script>
    @* <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v20.0" nonce="P6zkdA3O"></script> *@



    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

HuloToys-Front-End/Views/Shared/_BannerLarge.cshtml
@{
    Layout = null;
}
<div class="container">
    <div class="swiper swiper-banner">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <a href=""><img src="/assets/images/banner.jpg" alt="" /></a>
            </div>
            <div class="swiper-slide">
                <a href=""><img src="/assets/images/banner.jpg" alt="" /></a>
            </div>
            <div class="swiper-slide">
                <a href=""><img src="/assets/images/banner.jpg" alt="" /></a>
            </div>
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
</div>

HuloToys-Front-End/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}


<style>
    .li-Cursor
    {
        cursor : pointer;
    }

    .PromotionNoti {
        padding: 15px;
        border: 1px solid transparent;
        border-radius: 4px;
        background-color: #f0ad4e;
        color: #fff;
    }
</style>
<!-- Footer Start-->
<footer class="footer">
    <div class="container">
        <div class="topfooter">
            <div class="logo">
                <img src="/assets/images/logo-footer.png" alt="" />
                <h3 class="slogan">
                    Hulo Toys - Chuyên cung cấp các sản phẩm đồ chơi cho trẻ. Giúp em phát triển trí não,
                    nhằm kích thích tư duy, tính kiên trì, khả năng vận động qua từng món đồ chơi
                </h3>
                <a href="/dong-gop-y-kien" class="btn-gopy">Đóng góp ý kiến</a>
            </div>
            <div class="address">
                <ul>
                    <li><i class="icon icon-hotline"></i> 036 5809 316</li>
                    <li><i class="icon icon-map"></i> hulotoys@gmail.com</li>
                    <li>
                        <i class="icon icon-mail"></i> D25-47, Khu D, Khu đô thị Geleximco, Lê Trọng Tấn, Dương Nội, Hà
                        Đông, Hà Nội
                    </li>
                </ul>
            </div>
        </div>
        <div class="midfooter">
            <div class="col-links">
                <h4 class="tt-footer">VỀ HULO TOYS</h4>
                <ul class="AboutHulotoy-footer">
                    
                </ul>
            </div>
            <div class="col-links">
                <h4 class="tt-footer">CHĂM SÓC KHÁCH HÀNG</h4>
                <ul class="CustomerSupport-footer">
@*                     <li><a href="">Trải nghiệm mua sắm 100% hài lòng</a></li> *@
                    <li><a style="cursor:pointer" onclick="_support.GotoSearchBox()">Hỏi đáp - FAQs</a></li>
                </ul>
            </div>
            <div class="col-links">
                <h4 class="tt-footer">CHÍNH SÁCH</h4>
                <ul class="policy-footer">
                </ul>
            </div>
            <div class="col-links">
                <h4 class="tt-footer">CỘNG ĐỒNG HULOTOYS</h4>
                <ul>
                    <li><a href="/tin-tuc">Tin Tức</a></li>
                    <li><a href="https://www.facebook.com/hulotoys">Group Con ngoan</a></li>
                </ul>
            </div>
        </div>
        <div id="PromotionNoti" class="PromotionNoti" style="display:none;justify-content:center">
            <strong style="text-align:center">Thông báo:</strong>
        </div>
        <div class="bottomfooter">
            <div class="col-links">
                <h4 class="tt-footer">ĐĂNG KÍ NHẬN KHUYẾN MÃI</h4>
                <div class="form-search">
                    <form>
                        <input id="Email-text" type="text" placeholder="Nhập email của bạn">
                        <button type="button" onclick="_feedback.CreateEmailPromotion()" class="btn-search">Đăng kí</button>
                    </form>
                </div>
            </div>
            <div class="col-links">
                <h4 class="tt-footer">PHƯƠNG THỨC THANH TOÁN</h4>
                <div class="flex-col">
                    <ul>
                        <li><img src="/assets/images/mastercard.png" alt="" /></li>
                        <li><img src="/assets/images/jcb.png" alt="" /></li>
                        <li><img src="/assets/images/visa.png" alt="" /></li>
                    </ul>
                    <ul>
                        <li><a href="https://www.facebook.com/hulotoys"><i class="icon icon-facebook"></i></a></li>
                        @* <li><a href=""><i class="icon icon-instagram"></i></a></li> *@
                        <li><a href="@Html.Raw("https://www.tiktok.com/@hulo.toys?_r=1&_d=dgke6i40b2kj8f&sec_uid=MS4wLjABAAAAdn-rhy-rk0MtMkBpyeuJgoVKxklZHbIXgoXKy4CwTUEcglPvu1yZ_TG7lNNC6qDn&share_author_id=7318368424345371649&sharer_language=vi&source=h5_t&u_code=dj3ldm7e517i25&ug_btm=b6880,b5836&sec_user_id=MS4wLjABAAAACt-ik6Vb0POpjIT6KHmE3Jf-IobB4qUgenfK3qh80oqPJ8FWZnxgHUadKCXfggz5&utm_source=copy&social_share_type=5&utm_campaign=client_share&utm_medium=ios&tt_from=copy&user_id=6972604119156802562&enable_checksum=1&share_link_id=63B16E77-285B-4471-8AC1-D18055FBD119&share_app_id=1180")"><i class="icon icon-tiktok"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer End-->

HuloToys-Front-End/Views/Shared/_Header.cshtml
@{
    Layout = null;
}
<!-- Header Start -->
<header class="header">
    <div class="topbar">
        <div class="container">
            <div class="wrap_topbar">
                <div class="left_topbar">
                    <a href="/cham-soc-khach-hang"><i class="icon icon-hotro"></i>Hỗ trợ</a>
                    <a href=""><i class="icon icon-hotline"></i>Hotline: 036 5809 316</a>
                    <a href="/tin-tuc"><i class="icon icon-news"></i>Tin tức</a>
                </div>
                <div class="right_topbar" id="New_newDate" onload="_load_new_date.loadnew()">

                </div>
            </div>
        </div>
    </div>
    <div class="mainheader">
        <div class="container">
            <div class="wrap_mainheader">
                <div class="logo">
                    <a href="/"><img src="/assets/images/logo.png" alt=""></a>
                    
                </div>
                <div class="form-search">
                    @await Component.InvokeAsync("Search")

                   
                </div>
                <div class="right-mainheader">
                    <ul class="list-action">
                        <li>
                            <a href="/dong-gop-y-kien">
                                <i class="icon icon-comment"></i>
                                <span class="name">Đóng góp ý kiến</span>
                            </a>
                        </li>
                        <li class="notification">
                            <a href="">
                                <i class="icon icon-notifi"></i>
                                <span class="badge">10</span>
                                <span class="name">Thông báo</span>
                            </a>
                            <!-- Thông báo -->
                            <div class="box-noti">
                                <h3 class="title">Thông báo</h3>
                                <div class="list-noti">
                                    <div class="item">
                                        <div class="thumb-noti">
                                            <a href=""><img src="/assets/images/product.jpg" alt=""></a>
                                        </div>
                                        <div class="des">
                                            <a href="">
                                                <h3 class="title-noti">
                                                    Giao kiện hàng thành công
                                                </h3>
                                                <p>
                                                    Kiện hàng <b>VN123456789</b> của đơn hàng <b>123456789</b> đã giao
                                                    thành
                                                    công đến bạn
                                                </p>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="item readed">
                                        <div class="thumb-noti">
                                            <a href=""> <img src="/assets/images/product.jpg" alt=""></a>
                                        </div>
                                        <div class="des">
                                            <a href="">
                                                <h3 class="title-noti">
                                                    Giao kiện hàng thành công
                                                </h3>
                                                <p>
                                                    Kiện hàng <b>VN123456789</b> của đơn hàng <b>123456789</b> đã giao
                                                    thành
                                                    công đến bạn
                                                </p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="" class="xemtatca">Xem tất cả</a>
                            </div>
                        </li>
                        <li id="carts">
                            <a href="javascript:;" onclick="global_service.GotoCart()">
                                <i class="icon icon-cart"></i>
                                <span class="badge">0</span>
                                <span class="name">Giỏ hàng</span>
                            </a>
                        </li>
                        <li>
                            <a class="client-login" href="javascript:;" data-id="#dangnhap">
                                <i class="icon icon-user"></i>
                                <span id="client-account-name" class="name account-name">Tài khoản</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Header End -->

HuloToys-Front-End/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/jquery-ui.css">
    <link rel="stylesheet" href="/assets/css/select2.min.css">
    <link rel="stylesheet" href="/assets/css/lightgallery-bundle.css" />
    <link rel="stylesheet" href="/assets/css/main.min.css">
    <link rel="stylesheet" href="/custom/site.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet" />


    <title>@ViewData["Title"]</title>
    <link type="image/x-icon" href="~/images/img-search.png" rel="shortcut icon" />
    <!-- CSS-->

</head>
<body>
    <partial name="_Header" />
    <partial name="_Login" />

    <section id="main">
        @RenderBody()
    </section>
    <partial name="_Footer" />
    <button class="backToTopBtn"></button>
    <partial name="_Lightbox" />

    <script asp-append-version="true" src="/assets/js/jquery.min.js"></script>
    <script asp-append-version="true" src="/assets/js/swiper-bundle.min.js"></script>
    <script asp-append-version="true" src="/assets/js/jquery-ui.js"></script>
    <script asp-append-version="true" src="/assets/js/common.js"></script>
    <script asp-append-version="true" src="/custom/jquery.magnific-popup.min.js"></script>
    <script asp-append-version="true" src="/assets/js/select2.min.js"></script>
    <script src="/modules/constants.js" asp-append-version="true"></script>
    <script src="/modules/services.js" asp-append-version="true"></script>
    <script src="/modules/global.js" asp-append-version="true"></script>

    <!-- lightgallery-->
    <script src="/assets/js/lightgallery.min.js"></script>
    <script src="/assets/js/video.min.js"></script>
    <script src="/assets/js/lightgallery.umd.js"></script>
    <script src="/assets/js/lg-video.umd.js"></script>
    <script src="/assets/js/lg-thumbnail.min.js"></script>
    <!-- end lightgallery-->

    <!-- Modules-->
    <script asp-append-version="true" src="/modules/account.js"></script>
    <script asp-append-version="true" src="/modules/home_product.js"></script>
    <script asp-append-version="true" src="~/modules/support.js"></script>
    <script type="text/javascript" src="~/modules/feedback.js" asp-append-version="true"></script>
    <script src="https://accounts.google.com/gsi/client" async></script>
    @* <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v20.0" nonce="P6zkdA3O"></script> *@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
    


    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

HuloToys-Front-End/Views/Shared/_Lightbox.cshtml
@{
    Layout = null;
}

<!-- Lightbox thành công-->
<div id="thanhcong" class="overlay form-noti">
    <div class="popup">
        <a class="close" href="javascript:;">
            <i class="icon icon-close"></i>
        </a>
        <div class="content">
            <img src="/assets/images/check.svg" alt="">
            <h4>Thành công</h4>
            <p class="lightbox-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            <a href="javascript:;" class="btn btn-line btn-close">Đóng</a>
        </div>
    </div>
</div>
<div id="thatbai" class="overlay form-noti">
    <div class="popup">
        <a class="close" href="#">
            <i class="icon icon-close"></i>
        </a>
        <div class="content">
            <img src="/assets/images/error.svg" />
            <h4>LỖI</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            <a href="" class="btn btn-line">Đóng</a>
        </div>
    </div>
</div>
<div id="danhgia" class="overlay form-review">
    <div class="popup">
        <a class="close" href="javascript:;">
            <i class="icon icon-close"></i>
        </a>
        <h4 class="title">đánh giá</h4>
        <div class="content">
            <div class="list-product-rate">
                <div class="item">
                    <div class="box-product">
                        <div class="img">
                            <img src="/assets/images/product.jpg" alt="" />
                        </div>
                        <div class="info">
                            <h3 class="name-product">
                                Gấu Bông Mèo Hoàng Thượng Cosplay, Thú Nhồi Bông An Toàn
                                Cho Bé
                            </h3>
                            <div class="cat">Phân loại hàng: Gấu Trúc, 40cm</div>
                        </div>
                    </div>
                    <div class="star">
                        <span>Chất lượng sản phẩm</span>
                        <span class="rate five">
                            <i>★</i><i>★</i><i>★</i><i>★</i><i>★</i> Tuyệt vời
                        </span>
                    </div>
                    <div class="star">
                        <span>Chất lượng sản phẩm</span>
                        <span class="rate four">
                            <i>★</i><i>★</i><i>★</i><i>★</i><i>★</i> Hài lòng
                        </span>
                    </div>
                    <div class="star">
                        <span>Chất lượng sản phẩm</span>
                        <span class="rate three">
                            <i>★</i><i>★</i><i>★</i><i>★</i><i>★</i> Bình thường
                        </span>
                    </div>
                    <div class="star">
                        <span>Chất lượng sản phẩm</span>
                        <span class="rate two">
                            <i>★</i><i>★</i><i>★</i><i>★</i><i>★</i> Không hài lòng
                        </span>
                    </div>
                    <div class="star ">
                        <span>Chất lượng sản phẩm</span>
                        <span class="rate one">
                            <i>★</i><i>★</i><i>★</i><i>★</i><i>★</i> Tệ
                        </span>
                    </div>
                    <textarea rows="4" class="form-control"
                              placeholder="Hãy chia sẽ điều bạn thích về sản phẩm với những người mua khác nhé."></textarea>
                    <div class="upload-file">
                        <div class="uploadIMG">
                            <input type="file" class="upload" multiple/>
                            <span>Thêm hình ảnh</span>
                        </div>
                        <div class="uploadVIDEO">
                            <input type="file" class="upload" />
                            <span>Thêm video</span>
                        </div>
                    </div>
                    <div class="wrap-img-upload">
                        <div class="item">
                            <img src="./assets/images/product.jpg" alt="" />
                            <div class="del"></div>
                        </div>
                        <div class="item">
                            <img src="./assets/images/product.jpg" alt="" />
                            <div class="del"></div>
                        </div>
                        <div class="item">
                            <img src="./assets/images/product.jpg" alt="" />
                            <div class="del"></div>
                        </div>
                        <div class="uploadIMG">
                            <input type="file" class="upload" multiple />
                            <span>0/5</span>
                        </div>
                        <div class="uploadVIDEO">
                            <input type="file" class="upload" />
                            <span>0/1</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="action">
                <a href="javascript:;" class="btn btn-line btn-cancel">Trở lại</a>
                <a href="javascript:;" class="btn btn-base btn-confirm">Hoàn thành</a>
            </div>
        </div>

    </div>
</div>
<div id="dangxuat" class="overlay form-update-address">
    <div class="popup">
        <a class="close" href="javascript:;">
            <i class="icon icon-close"></i>
        </a>
        <div class="content">
            <h4 class="title-popup">Xác nhận đăng xuất tài khoản?</h4>
            <div class="action">
                <a href="javascript:;" class="btn btn-cancel">Hủy</a>
                <a id="account-logout" href="javascript:;" class="btn btn-base btn-logout">Đăng xuất</a>
            </div>
        </div>
    </div>
</div>

HuloToys-Front-End/Views/Shared/_MenuLeftUser.cshtml
@{
    Layout = null;
}
<div class="header-user">
    <div class="avatar">
        <img src="/assets/images/product.jpg" alt="">
    </div>
    <div class="box-name">
        <span class="sayhi">Xin chào bạn</span>
        <h3 class="name">Lê Văn Cường</h3>
    </div>
</div>
<div class="list-tab-menu">
    <ul>
        <li class="sub-menu">
            <span><i class="icon icon-user-base"></i> Thông tin tài khoản </span>
            <ul>
                <li class="client-detail"><a href="javascript:;">Hồ sơ</a></li>
                <li class="client-address"><a href="/Client/Address">Địa chỉ</a></li>
                <li class="client-password"><a href="javascript:;">Đổi mật khẩu</a></li>
            </ul>
        </li>
        <li class="my-order-detail">
            <a href="/order"><i class="icon icon-order"></i>Đơn hàng của tôi</a>
        </li>
        <li class="sub-menu">
            <span><i class="icon icon-notifi-base"></i>Thông báo</span>
            <ul>
                <li class="orders"><a href="javascript:;">Đơn hàng</a></li>
                <li class="sale"><a href="javascript:;">Khuyến mãi</a></li>
            </ul>
        </li>
        <li>
            <a href="javascript:;"><i class="icon icon-like"></i>Sản phẩm yêu thích</a>
        </li>
        <li>
            <a id="logout-action" href="javascript:;">Đăng xuất</a>
        </li>
    </ul>
</div>